### ISSUE TITLE
Complete the game

### ISSUE THREAD

**Issue by tibrewalpratik17** [tibrewalpratik17/2048_#1]
Write codes for moveup, moveleft and moveright as for movedown.

**Comment by SomeshThakur** [comment]
@tibrewalpratik17 Does the game building environment requires any specific packages ? And can we build it in Windows IDE like Pycharm?

**Comment by tibrewalpratik17** [comment]
@SomeshThakur I am particularly looking for implementing this in Pygame and for further queries please use the google group.

**Comment by vegeta1509** [comment]
@tibrewalpratik17 I am working on further codes.
